name: "Lint with clj-kondo"
on:
  pull_request:
  push:
    branches:
      - live

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.06.18'

      - uses: actions/checkout@latest

      - name: Run on Ubuntu
        run: clj-kondo --lint deps.edn
